const people = [
  //Presidents
  "Abdelaziz Bouteflika",
  "Abdelkader Bensalah",
  "Ahmed Ouyahia",
  "Noureddine Bedoui",
  "João Lourenço",
  "Patrice Talon",
  "Mokgweetsi Masisi",
  "Roch Marc Christian Kaboré",
  "Paul Kaba Thieba",
  "Christophe Joseph Marie Dabiré",
  "Pierre Nkurunziza",
  "Paul Biya",
  "Philémon Yang",
  "Joseph Ngute",
  "Jorge Carlos Fonseca",
  "Ulisses Correia e Silva",
  "Faustin-Archange Touadéra",
  "Simplice Sarandji",
  "Firmin Ngrébada",
  "Idriss Déby",
  "Azali Assoumani",
  "Moustadroine Abdou",
  "Denis Sassou Nguesso",
  "Clément Mouamba",
  "Joseph Kabila",
  "Félix Tshisekedi",
  "Bruno Tshibala",
  "Sylvestre Ilunga",
  "Ismaïl Omar Guelleh",
  "Abdoulkader Kamil Mohamed",
  "Abdel Fattah el-Sisi",
  "Moustafa Madbouly",
  "Teodoro Obiang Nguema Mbasogo",
  "Francisco Pascual Obama Asue",
  "Isaias Afwerki",
  "Mswati III",
  "Mandvulo Ambrose Dlamini",
  "Sahle-Work Zewde",
  "Abiy Ahmed",
  "Ali Bongo Ondimba",
  "Emmanuel Issoze-Ngondet",
  "Julien Nkoghe Bekale",
  "Adama Barrow",
  "Nana Akufo-Addo",
  "Alpha Condé",
  "Ibrahima Kassory Fofana",
  "José Mário Vaz",
  "Cipriano Cassamá",
  "Aristides Gomes",
  "Alassane Ouattara",
  "Amadou Gon Coulibaly",
  "Uhuru Kenyatta",
  "Letsie III",
  "Tom Thabane",
  "George Weah",
  "Aguila Saleh Issa",
  "Abdullah al-Thani",
  "Fayez al-Sarraj",
  "Rivo Rakotovao",
  "Andry Rajoelina",
  "Christian Ntsay",
  "Peter Mutharika",
  "Ibrahim Boubacar Keïta",
  "Soumeylou Boubèye Maïga",
  "Boubou Cisse",
  "Mohamed Ould Abdel Aziz",
  "Mohamed Salem Ould Béchir",
  "Barlen Vyapoory",
  "Pravind Jugnauth",
  "Donald Trump",
  "Barack Obama",
  "Hillary Clinton",
  "Robert Mueller",
  "Brett Kavanaugh",
  "Vladimir Putin",
  "Kim Jong Un",
  "George W. Bush",
  "Jeff Sessions",
  "Mike Pence",
  "LeBron James",
  "Mike Pompeo",
  "Michael Cohen",
  "Mitch McConnell",
  "Bill Clinton",
  "Paul Ryan",
  "Sarah Huckabee Sanders",
  "Nancy Pelosi",
  "Tom Brady",
  "John McCain",
  "Emmanuel Macron",
  "Melania Trump",
  "Christine Blasey Ford",
  "Rick Scott",
  "Chuck Schumer",
  "Kevin Durant",
  "Paul Manafort",
  "George H.W. Bush",
  "Harvey Weinstein",
  "Pope Francis",
  "James Comey",
  "Xi Jinping",
  "Bernie Sanders",
  "Jerry Brown",
  "Ronald Reagan",
  "Mark Zuckerberg",
  "Moon Jae-in",
  "Angela Merkel",
  "Stephen Curry",
  "Jeff Flake",
  "Jamal Khashoggi",
  "John Kelly",
  "Jared Kushner",
  "Jesus Christ",
  "Ted Cruz",
  "Aaron Rodgers",
  "Andrew Cuomo",
  "Theresa May",
  "Rod Rosenstein",
  "Lindsey Graham",
  "Tiger Woods",
  "Scott Walker",
  "Dianne Feinstein",
  "Larry Nassar",
  "Meghan Markle",
  "Jim Mattis",
  "Nikolas Cruz",
  "Steve Kerr",
  "James Harden",
  "John Bolton",
  "Benjamin Netanyahu",
  "Anthony Kennedy",
  "Rudy Giuliani",
  "Susan Collins",
  "Bill Belichick",
  "Tayyip Erdogan",
  "Rex Tillerson",
  "Klay Thompson",
  "Mohammed bin Salman",
  "Joe Biden",
  "Bashar Assad",
  "Baker Mayfield",
  "Chris Paul",
  "Chuck Grassley",
  "Ivanka Trump",
  "Elizabeth Warren",
  "Donald Trump Jr.",
  "Alex Cora",
  "Jeff Bezos",
  "Steve Bannon",
  "Marco Rubio",
  "Richard Nixon",
  "Kirstjen Nielsen",
  "Bill Nelson",
  "Colin Kaepernick",
  "Michael Avenatti",
  "Jon Gruden",
  "Scott Pruitt",
  "Manny Machado",
  "Doug Ducey",
  "Bill Cosby",
  "Justin Trudeau",
  "Martin Luther King Jr.",
  "J.D. Martinez",
  "Nikki Haley",
  "Mookie Betts",
  "Oprah Winfrey",
  "Steven Mnuchin",
  "Elon Musk",
  "Michael Flynn",

  // Picked out: Politics
  "Trump",
  "Donald Trump",
  "President Trump",
  "Xi Jinping",
  "Joseph R. Biden Jr.",
  "Biden",
  "Barack Obama",
  "Obama",
  "Robert O'Brien",
  "Kamala Harris",
  "Cory Booker",
  "Bill de Blasio",
  "Julián Castro",
  "Castro",

  // Picked out: Business
  "Brian Grazer",
  "Ron Howard",
  "Adam Kizinger",
  "Jeffery Epstein",
  "Epstein",
  "Tyler Blevins",
  "Leon Black",
  "Black",
  "Gary Rosenblatt",
  "Austan Goolsbee",
  "Liu Zhongtian",
  "Dominic King",
  "Robert Lighthizer",
  "Liu He",

  // Picked out: Technology
  "John Herrman",
  "John F. Mitchell",
  "Walsh",
  "Alison Grace Martin",
  "Renee Holland",

  // Picked out: World
  "Abdoulie Barry",
  "Osama bin Laden",
  "Mike Pompeo",
  "Walid Fitaihi",
  "Mohammad Javad Zarif",
  "Abdirahman Omar Osman",
  "Boris Johnson",
  "Antonio Guterres",
  "Dai Fujikura",
  "Mahmoud Afif Abdeljalil",
  "Hal Prince",
  "Mashrou’ Leila"
];

module.exports = people;
