const people = [
  //Presidents
  "Peter Mutharika",
  "Ibrahim Boubacar Keïta",
  "Soumeylou Boubèye Maïga",
  "Boubou Cisse",
  "Mohamed Ould Abdel Aziz",
  "Mohamed Salem Ould Béchir",
  "Barlen Vyapoory",
  "Pravind Jugnauth",
  // "Donald Trump",
  // "Barack Obama",
  "Hillary Clinton",
  "Robert Mueller",
  "Brett Kavanaugh",
  "Vladimir Putin",
  "Kim Jong Un",
  "George W. Bush",
  "Jeff Sessions",
  "Mike Pence",
  "LeBron James",
  "Mike Pompeo",
  "Michael Cohen",
  "Mitch McConnell",
  "Bill Clinton",
  "Paul Ryan",
  "Sarah Huckabee Sanders",
  "Nancy Pelosi",
  "Tom Brady",
  "John McCain",
  "Emmanuel Macron",
  "Melania Trump",
  "Christine Blasey Ford",
  "Rick Scott",
  "Chuck Schumer",
  "Kevin Durant",
  "Paul Manafort",
  "George H.W. Bush",
  "Harvey Weinstein",
  "Pope Francis",
  "James Comey",
  "Xi Jinping",
  "Bernie Sanders",
  "Jerry Brown",
  "Ronald Reagan",
  "Mark Zuckerberg",
  "Moon Jae-in",
  "Angela Merkel",
  "Stephen Curry",
  "Jeff Flake",
  "Jamal Khashoggi",
  "John Kelly",
  "Jared Kushner",
  "Jesus Christ",
  "Ted Cruz",
  "Aaron Rodgers",
  "Andrew Cuomo",
  "Theresa May",
  "Rod Rosenstein",
  "Lindsey Graham",
  "Tiger Woods",
  "Scott Walker",
  "Dianne Feinstein",
  "Larry Nassar",
  "Meghan Markle",
  "Jim Mattis",
  "Nikolas Cruz",
  "Steve Kerr",
  "James Harden",
  "John Bolton",
  "Benjamin Netanyahu",
  "Anthony Kennedy",
  "Rudy Giuliani",
  "Susan Collins",
  "Bill Belichick",
  "Tayyip Erdogan",
  "Rex Tillerson",
  "Klay Thompson",
  "Mohammed bin Salman",
  "Joe Biden",
  "Bashar Assad",
  "Baker Mayfield",
  "Chris Paul",
  "Chuck Grassley",
  "Ivanka Trump",
  "Elizabeth Warren",
  "Donald Trump Jr.",
  "Alex Cora",
  "Jeff Bezos",
  "Steve Bannon",
  "Marco Rubio",
  "Richard Nixon",
  "Kirstjen Nielsen",
  "Bill Nelson",
  "Colin Kaepernick",
  "Michael Avenatti",
  "Jon Gruden",
  "Scott Pruitt",
  "Manny Machado",
  "Doug Ducey",
  "Bill Cosby",
  "Justin Trudeau",
  "Martin Luther King Jr.",
  "J.D. Martinez",
  "Nikki Haley",
  "Mookie Betts",
  "Oprah Winfrey",
  "Steven Mnuchin",
  "Elon Musk",
  "Michael Flynn",

  // Picked out: Politics
  // "Trump",
  "Donald Trump",
  "President Trump",
  "Xi Jinping",
  "Joseph R. Biden Jr.",
  // "Biden",
  "Barack Obama",
  // "Obama",
  "Robert O'Brien",
  "Kamala Harris",
  "Cory Booker",
  "Bill de Blasio",
  "Julián Castro",
  // "Castro",

  // Picked out: Business
  "Brian Grazer",
  "Ron Howard",
  "Adam Kizinger",
  "Jeffery Epstein",
  "Epstein",
  "Tyler Blevins",
  "Leon Black",
  "Black",
  "Gary Rosenblatt",
  "Austan Goolsbee",
  "Liu Zhongtian",
  "Dominic King",
  "Robert Lighthizer",
  "Liu He",

  // Picked out: Technology
  "John Herrman",
  "John F. Mitchell",
  "Walsh",
  "Alison Grace Martin",
  "Renee Holland",

  // Picked out: World
  "Abdoulie Barry",
  "Osama bin Laden",
  "Mike Pompeo",
  "Walid Fitaihi",
  "Mohammad Javad Zarif",
  "Abdirahman Omar Osman",
  "Boris Johnson",
  "Antonio Guterres",
  "Dai Fujikura",
  "Mahmoud Afif Abdeljalil",
  "Hal Prince",
  "Mashrou’ Leila"
];

module.exports = people;
